-- Arbor — apply 0007 (asset financials) + 0008 (chemical subsectors). Paste & Run.

-- ============================================================================
-- Arbor — per-asset financials + branding (radar card + company page).
-- Idempotent. Apply after 0006_taxonomy.sql. All nullable — populated later by
-- ingestion / manual entry. (description already exists from 0001.)
-- ============================================================================

alter table public.companies add column if not exists logo_url            text;
alter table public.companies add column if not exists revenue             text;  -- e.g. "$1.2B"
alter table public.companies add column if not exists ebitda              text;  -- e.g. "$280M"
alter table public.companies add column if not exists margin              text;  -- e.g. "23%"
alter table public.companies add column if not exists revenue_source_url  text;  -- filing / press release
alter table public.companies add column if not exists ebitda_source_url   text;

-- ============================================================================
-- Arbor — best-effort subsector for §2.2 Chemicals deals (generated by
-- scripts/gen-chem-subsectors.mjs). Idempotent. Apply after 0007.
-- Only touches rows with the 'Added to Chemicals radar' history marker, so demo
-- companies sharing a name are left alone.
-- ============================================================================

update public.companies c
set subsector = v.subsector
from (values
  ('AMVAC', 'Specialties'),
  ('Bioceres Crop Solutions', 'Specialties'),
  ('Calumet TruFuel', 'Specialties'),
  ('Dow Polyurethanes', 'Intermediates'),
  ('FMC', 'Chemicals'),
  ('Ingevity Advanced Polymer Technologies', 'Specialties'),
  ('Nutrien Brazilian Soybean Business', 'Chemicals'),
  ('Nutrien Phosphates', 'Chemicals'),
  ('Solvay Flurochemicals', 'Specialties'),
  ('Total Styrene and Polystyrene Plant', 'Intermediates'),
  ('Trinseo', 'Intermediates'),
  ('AmSty', 'Intermediates'),
  ('Celanese Infraserv', 'Intermediates'),
  ('Celanese Teijin Films JV', 'Specialties'),
  ('Hexion Versatic Acids', 'Specialties'),
  ('Mosaic Brazil Assets', 'Chemicals'),
  ('Shell U.S. Chemical Assets', 'Chemicals'),
  ('Beaulieu International Group / Pinnacle Polymers', 'Intermediates'),
  ('Braskem U.S. Assets', 'Intermediates'),
  ('Cargill Deicing Salt', 'Chemicals'),
  ('Compass Minerals Arizona Chemical', 'Chemicals'),
  ('IDL Chemical', 'Specialties'),
  ('Element Solutions', 'Specialties'),
  ('HF Sinclair Lubricants and Specialties', 'Specialties'),
  ('Invista Nylon 6,6 Plants', 'Intermediates'),
  ('Syngenta Group non Ag/crop business', 'Specialties'),
  ('Shell Phenol A', 'Intermediates'),
  ('Boulder Scientific Company', 'Specialties'),
  ('Chroma', 'Specialties'),
  ('Delrin', 'Intermediates'),
  ('Drew Marine', 'Specialties'),
  ('EPSilyte', 'Intermediates'),
  ('Fralock', 'Specialties'),
  ('gChem', 'Specialties'),
  ('Prince Izant', 'Specialties'),
  ('Old World Industries', 'Specialties'),
  ('Osterman', 'Specialties'),
  ('Weitron', 'Specialties'),
  ('Altivia', 'Specialties'),
  ('AluChem', 'Specialties'),
  ('Barrday', 'Specialties'),
  ('Carbide Industries LLC', 'Chemicals'),
  ('Covia', 'Chemicals'),
  ('Dixie Chemical', 'Specialties'),
  ('DK (unnamed)', 'Specialties'),
  ('GEON', 'Intermediates'),
  ('Greene Weed', 'Specialties'),
  ('Meridian', 'Specialties'),
  ('Microporous', 'Specialties'),
  ('Miraclon', 'Specialties'),
  ('Polytek Development Corp.', 'Specialties'),
  ('Sachem', 'Specialties'),
  ('SafeChem', 'Specialties'),
  ('Shamrock', 'Specialties'),
  ('Shrieve', 'Specialties'),
  ('Tilley Distribution', 'Specialties'),
  ('Vincit', 'Specialties'),
  ('Wakefield', 'Specialties'),
  ('AgXplore', 'Specialties'),
  ('Connection Chemical', 'Specialties'),
  ('FXI', 'Intermediates'),
  ('Innophos', 'Specialties'),
  ('Isola', 'Specialties'),
  ('Lion Elastomers', 'Intermediates'),
  ('Microban', 'Specialties'),
  ('TPC Group', 'Intermediates'),
  ('Valudor Products LLC', 'Specialties'),
  ('Vantage', 'Specialties')
) as v(name, subsector)
where c.name = v.name
  and c.sector = 'chemicals'
  and exists (
    select 1 from public.deal_stage_history h
    where h.company_id = c.id
      and h.headline = 'Added to Chemicals radar — ' || c.name
  );
